apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-operator
  labels:
    app.kubernetes.io/name: sandbox-operator
    app.kubernetes.io/version: v0.10.0
spec:
  selector:
    matchLabels:
      name: sandbox-operator
  template:
    metadata:
      labels:
        name: sandbox-operator
    spec:
      serviceAccountName: sandbox-operator-sa
      containers:
        - name: sandbox-operator
          image: plexsystems/sandbox-operator:v0.10.0
          command:
          - sandbox-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: OPERATOR_NAME
              value: "sandbox-operator"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
